name: PaNOSC - Data Transfer Pilot
channels:
- conda-forge
dependencies:
- matplotlib
- pillow
- pip
- pip:
  - git+https://github.com/EGI-Foundation/egi-notebooks-addons
  - git+https://github.com/onedata/fs-onedatafs.git@19.02.2
  - git+https://github.com/enolfc/onedatafs.git@19.02.1
  - git+https://github.com/onedata/onedatafs-jupyter.git@19.02.2
